<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="150">
</p>

<h1> Matemáticas para ciencia de datos</h1>

#### Pofra. Dra. Olivia Gutú

<h3>Tarea 1</h3>

#### Diana Laura Ballesteros Valenzuela

<img src="https://identidadbuho.unison.mx/wp-content/uploads/2019/06/letragrama-cmyk-72.jpg" width="150">

</center>

Importamos librerias necesarias

In [1]:
import pandas as pd
import numpy as np
import sympy

#### Sea A una matriz de datos dada por el archivo dataset.csv

In [16]:
A = pd.read_csv("dataset.csv", header=None)

- **Sospechamos que nuestra matriz de datos tiene columnas redundantes (se pueden ponercomo combinaciones lineales de las otras) por la naturaleza de su creacion, ¿cual es el maximo numero de columnas linealmente independiente que puede tener A?**

In [3]:
rank = np.linalg.matrix_rank(A)
rank

5

> R= Vemos que su rank es de 5, por lo tanto, su máximo numero de columnas linealmente independientes es 5.

- **Supon que quieres borrar de A las columnas que dependan linealmente de otras sin sacrificar la dimension de su rango (su rank). Una primera busqueda por el internet nos arroja la siguiente respuesta misteriosa muy relacionada aquı:**

> [. . . ] One way to do what you want is to apply numpy.linalg.qr to the transpose, and check the non-zero components of the R matrix. The corresponding columns (in the transpose matrix, i.e., the rows in your original matrix) are independent.

Es decir, pide considerar la descomposion de A = QR, aquı Q es una matriz ortogonal (columnas y renglones ortogonales entre sı) y R una matriz triangular superior con las entradas debajo de la diagonal principal son cero. ¿Es correcta esta respuesta? Justifica tu respuesta con un contra-ejemplo o da una serie de razonamientos para justificar que la respuesta es correcta.

- **Elimina efectivamente de A las columnas que sean combinaciones lineales de otras. ¿Hay una sola manera de hacer esto? Identifica si te es posible las relaciones lineales de la columnas eliminadas respecto a las otras.**

In [4]:
a=np.array(A)
my_array = np.linalg.qr(a)[1]

In [5]:
df2 = pd.DataFrame(my_array).round()
df2

0       1       2       3       4       5       6       7
0 -2405.0 -2404.0 -2460.0 -2283.0 -2387.0 -2404.0 -2424.0 -2395.0
1     0.0  -193.0  -207.0  -197.0  -244.0   -96.0  -226.0  -166.0
2     0.0     0.0  -181.0  -146.0  -200.0    -0.0  -191.0  -102.0
3     0.0     0.0     0.0  -214.0  -122.0    -0.0   -61.0   -57.0
4     0.0     0.0     0.0     0.0  -182.0    -0.0   -91.0   -39.0
5     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
6     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
7     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

Podemos ver que podemos eliminar las columnas 6,7 y 8 ya que son redundantes

- **Sea 1 el vector de solo unos en Rn. Para cada x ∈ Rn sea xcentered = x − µ1 donde µ es el promedio de los elementos de x (sample mean). Responde las siguientes preguntas:**


**1.** Sea A_centered la matriz que resulta de centrar cada columna de A. ¿Que efecto geometrico tiene sobre A este procedimiento?

 - El efecto geometrico es que enviaria todo al cero

**2.** Responde si x y y son dos columnas de A linealmente independientes, ¿tambien lo son x_centered y y_centered?

In [6]:
matrixIndependiente = A[[0, 1, 2, 3, 4, 5]] #Usamos las columnas de A que solo son independientes
df_centered = matrixIndependiente.apply(lambda x: x-x.mean())

print(sympy.Matrix(matrixIndependiente.iloc[:, 0:-1].round()).nullspace())
print(sympy.Matrix(df_centered.iloc[:, 0:-1].round()).nullspace())

[]
[]


Todas las columnas de Acentered tambien son linealmente independientes

**3.** Responde si x y y son dos columnas de A ortogonales, ¿tambien lo son x_centered y y_centered?

> 📝 **NOTA**: Intente buscar columnas ortogonales en A y no hubo alguna pareja de columnas que me diera la matriz unitaria, por lo que tomare de ejemplo otra matriz para ver que me da de resultado

Pongamos de ejemplo la matriz M

In [7]:
A= pd.DataFrame(([[-1,0],[0,1]]))

y veamos si es ortogonal

In [8]:
matrix = np.array(A)

In [9]:
res = pd.DataFrame(np.dot(matrix,matrix.transpose())).round()
res

0  1
0  1  0
1  0  1

Vemos que el producto punto de la matrix A por su transpuesta nos da la matriz identidad, por lo que si son ortogonales. Ahora saquemos x_centered y y_centered y veamos si su producto punto es igual a la identidad

In [10]:
xy_centered = np.array(pd.DataFrame(A.apply(lambda x: x-x.mean())).round())
xy_centered

array([[-0., -0.],
       [ 0.,  0.]])

In [11]:
res = pd.DataFrame(np.dot(xy_centered,xy_centered.transpose())).round() #aplicamos producto punto y lo convertimos a dataframe para cuestiones esteticas
res

0    1
0  0.0  0.0
1  0.0  0.0

> Vemos que x_entered y y_centered no son ortogonales ya que como resultado NO tenemos la matriz identidad

4. ¿Cual es la media de cualquier vector x_centered ?

In [12]:
# la respuesta es 0 y para cada vector de A
for x in range(0, A.shape[1]):
    print(np.mean(df_centered[x]).round())

0.0
-0.0


5. Para cada x, encuentra el vector unitario con direccion x_centered

In [13]:
# la respuesta es 0 y para cada vector de A
for x in range(0, A.shape[1]):
    print(np.mean(df_centered[x] / np.linalg.norm(df_centered[x])))

2.9309887850104133e-18
-6.8389738316909645e-18


- **Encuentra, si existe, la/una combinacion lineal de las primeras 2 columnas mas cercana a la columna numero 6.**

In [17]:
primeras2columnas = np.array(A[[0,1]]) #Filtramos las columnas que queremos
columna6 = np.array(A[[5]]) #Filtramos las columnas que queremos
unodos = np.column_stack((primeras2columnas))

# Ax=B
# x = A^-1*b
pseudoInversa = np.linalg.pinv(primeras2columnas)
x = np.dot(pseudoInversa,columna6)
x

array([[0.5],
       [0.5]])

Haz lo mismo pero con las primeras 3, 4 y 5 columnas. En cada caso decide si la respuesta existe y es unica.


In [18]:
columnas34 = np.array(A[[2,3]]) #Filtramos las columnas que queremos
trescuatro = np.column_stack((columnas34))
columna5 = np.array(A[[4]]) #Filtramos las columnas que queremos

pseudoInversa = np.linalg.pinv(columnas34)
x = np.dot(pseudoInversa,columna5)
x

array([[0.4570231],
       [0.5556962]])